version: "2.0"
services:
  playlistsuggestion-ws:
    build: ./playlistsuggestion-ws
    environment:
      - OPEN_WEATHER_KEY=<YOUR_OPEN_WEATHER_KEY>
      - SPOTIFY_ID=<YOUR_SPOTIFY_CLIENT_ID>
      - SPOTIFY_SECRET=<YOUR_SPOTIFY_CLIENT_SECRET>
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - activemq
      - redis
      - postgis
    links:
      - activemq
      - redis
      - postgis
    networks:
      - playlistsuggestion-net
  playlistsuggestion-worker:
    build: ./playlistsuggestion-worker
    environment:
      - OPEN_WEATHER_KEY=<YOUR_OPEN_WEATHER_KEY>
      - SPOTIFY_ID=<YOUR_SPOTIFY_CLIENT_ID>
      - SPOTIFY_SECRET=<YOUR_SPOTIFY_CLIENT_SECRET>
    expose:
      - 8090
    ports:
      - 8090:8090
    depends_on:
      - activemq
      - redis
      - postgis
    links:
      - activemq
      - redis
      - postgis
    networks:
      - playlistsuggestion-net
  activemq:
    image: webcenter/activemq:latest
    container_name: playlistsuggestion-activemq
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
    networks:
      - playlistsuggestion-net      
  redis:
    image: redis:latest
    container_name: playlistsuggestion-redis
    ports:
      - 6379:6379 
    networks:
      - playlistsuggestion-net
  postgis:
    image: mdillon/postgis:latest
    container_name: playlistsuggestion-postgis
    ports:
      - 5432:5432
    networks:
      - playlistsuggestion-net
networks:
  playlistsuggestion-net:
    driver: bridge